(deftheme johnsogg-light
  "Created 2017-05-12.")

(custom-theme-set-variables
 'johnsogg-light
 '(ansi-color-names-vector ["#ffffff" "#183691" "#969896" "#a71d5d" "#969896" "#969896" "#795da3" "#969896"]))

(custom-theme-set-faces
 'johnsogg-light
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#a71d5d" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#333333" :underline t :weight normal))))
 '(cursor ((t (:foreground "#333333" :background "#333333"))))
 '(escape-glyph ((t (:foreground "#a71d5d" :bold t))))
 '(fringe ((t (:foreground "#333333" :background "#ffffff"))))
 '(header-line ((t (:foreground "#a71d5d" :background "#b0cde7" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#f8eec7"))))
 '(success ((t (:foreground "#969896" :weight bold))))
 '(warning ((t (:foreground "#333333" :weight bold))))
 '(tooltip ((t (:foreground "#333333" :background "#ffffff"))))
 '(compilation-info ((t (:foreground "#0086b3" :underline t))))
 '(compilation-line-number ((t (:foreground "#a71d5d"))))
 '(compilation-mode-line-exit ((t (:foreground "#969896" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#183691" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#a71d5d" :weight bold))))
 '(completions-annotations ((t (:foreground "#333333"))))
 '(match ((t (:background "#b0cde7" :foreground "#333333" :weight bold))))
 '(isearch ((t (:foreground "#ffffff" :weight bold :background "#b0cde7"))))
 '(isearch-fail ((t (:foreground "#d0d0d0" :background "#ffffff"))))
 '(lazy-highlight ((t (:foreground "#333333" :weight bold :background "#f8eec7"))))
 '(menu ((t (:foreground "#333333" :background "#ffffff"))))
 '(minibuffer-prompt ((t (:foreground "#a71d5d"))))
 '(mode-line ((t (:background "#d0d0d0" :foreground "#202020"))))
 '(mode-line-buffer-id ((t (:foreground "#000000" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#969896" :background "#ffffff" :box (:line-width -1 :color "#d0d0d0")))))
 '(region ((((class color) (min-colors 89)) (:background "#b0cde7")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#ffffff"))))
 '(trailing-whitespace ((t (:background "#183691"))))
 '(vertical-border ((t (:foreground "#d0d0d0"))))
 '(font-lock-builtin-face ((t (:foreground "#a71d5d"))))
 '(font-lock-comment-face ((t (:foreground "#969896"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#969896"))))
 '(font-lock-constant-face ((t (:foreground "#0086b3"))))
 '(font-lock-doc-face ((t (:foreground "#183691"))))
 '(font-lock-function-name-face ((t (:foreground "#795da3"))))
 '(font-lock-keyword-face ((t (:foreground "#a71d5d"))))
 '(font-lock-negation-char-face ((t (:foreground "#a71d5d"))))
 '(font-lock-preprocessor-face ((t (:foreground "#a71d5d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#a71d5d"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#969896"))))
 '(font-lock-string-face ((t (:foreground "#183691"))))
 '(font-lock-type-face ((t (:foreground "#0086b3"))))
 '(font-lock-variable-name-face ((t (:foreground "#333333"))))
 '(font-lock-warning-face ((t (:foreground "#333333"))))
 '(ac-candidate-face ((t (:background "#ffffff" :foreground "#333333"))))
 '(ac-completion-face ((t (:background "#b0cde7" :foreground "#333333"))))
 '(ac-selection-face ((t (:background "#b0cde7" :foreground "#333333"))))
 '(popup-tip-face ((t (:background "#333333" :foreground "#ffffff"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#333333"))))
 '(popup-scroll-bar-background-face ((t (:background "#969896"))))
 '(popup-isearch-match ((t (:background "#ffffff" :foreground "#333333"))))
 '(diff-added ((t (:background "#eaffea" :foreground "#333333"))))
 '(diff-changed ((t (:background "#f8cca9" :foreground "#333333"))))
 '(diff-removed ((t (:background "#ffecec" :foreground "#333333"))))
 '(diff-refine-added ((t (:background "#a6f3a6" :foreground "#333333"))))
 '(diff-refine-changed ((t (:background "#f6dac3" :foreground "#333333"))))
 '(diff-refine-removed ((t (:background "#f8cbcb" :foreground "#333333"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#ffffff")) (t (:background "#333333" :foreground "#ffffff"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#ffffff" :foreground "#333333" :bold t)) (t (:background "#333333" :foreground "#ffffff" :bold t))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#183691") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#333333" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#333333") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#333333" :weight bold :underline t))))
 '(show-paren-mismatch ((t (:foreground "#969896" :background "#ffffff" :weight bold))))
 '(show-paren-match ((t (:background "#d2d8e0" :weight bold))))
 '(default ((t (:foreground "#333333" :background "#ffffff")))))

(provide-theme 'johnsogg-light)
